### ISSUE TITLE
Добавить файл конфигурации

### ISSUE THREAD

**Issue by olegpolyakov** [gajet5/betaDumpServer#1]
`Error: Cannot find module './config'`

**Comment by olegpolyakov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Выполнить ДЗ №1](https://trello.com/c/pO8qmbAi/2-%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D1%8C-%D0%B4%D0%B7-%E2%84%961)

**Comment by gajet5** [comment]
Файл конфигурации несёт в себе информацию которую я не хотел бы выкладывать в публичный доступ. Я его принудительно игнорю.

**Comment by gajet5** [comment]
Obsolete
